version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_DATABASE: plannerData
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports: 
      - "3306:3306"